const EventDetails = [
  {
    key: 1,
    url: "https://i.postimg.cc/6QNbS4gj/Paper-Crafting.webp",
    name: "PAPER CRAFTING",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/1lXNPsXNbKVqpDkszwMI7sAaP8AyUowHtYL2H2qf-xO8/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/1-mA5jFRTQcJwCkBwF0hclef_lr-GmWp2KIz3f83BWz4/edit"
  },
  {
    key: 2,
    url: "https://i.postimg.cc/d1jbnj0j/Circuit-Design.webp",
    name: "CIRCUIT DESIGN",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/1I5Ns5nZTdA-8lGYOaX8y_sCRjkUwwZxFz3pMPl-FDrA/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/1ajaKKCxnxNHJg1yU8Zi5mT58INGV2EZZBkSHN1W4FNU/edit"
  },
  {
    key: 3,
    url: "https://i.postimg.cc/tJzMtq2S/Online-Gaming.webp",
    name: "ONLINE GAMING",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/1fEv-o3UUI7de85eqcysVGYdPtk3PEwp1tTmsHsk-es0/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/1SE0z06wrZzVT3vr1-Aiq5IxP8FS6Iq1CvUFpS4dvKC8/edit"
  },

  {
    key: 4,
    url: "https://i.postimg.cc/PJH7wpzv/Quiz.webp",
    name: "QUIZ",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/1fySqLxeFVLPYV-j-noyxpsztenMRS1_qS5vySX-Go-c/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/1qzIsVYouhxotyh7Vigv3lgIdrVHBMXiLXAQTZwnuPb4/edit"
  },
  {
    key: 5,
    url: "https://i.postimg.cc/9f2kNSb4/Coding.webp",
    name: "FUN WITH CODING",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/1tgpopQegwj8qLWSOf_GTFI3xQ104R_N9Ie_6FEVdrac/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/1Q9xAsqpRPmgLU1CBagUY_-muNOUpfE__O-JtDbHnR2w/edit"
  },
  {
    key: 6,
    url: "https://i.postimg.cc/6pnScwrJ/Jam.webp",
    name: "JAM",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/1s_F-V795fwuuDGYoytpJfhDELZ9xVbpT0i2EeMDSTyI/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/13mtHH18FOq_qywF87OTUIh0gXxT3W_mzl8HGLCKXbSY/edit"
  },
  {
    key: 7,
    url: "https://i.postimg.cc/pr2Ht1SS/Face-Painting.webp",
    name: "FACE PAINTING",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/1nhDzunRoM3mIvwXjQWfHXLfoN0gKLmYIRqgpjOwS5fA/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/1naaOk5_47qC0lkMUMfMBLhp6qOj-5rJh8i9Xie-M0lY/edit"
  },
  
  {
    key: 8,
    url: "https://i.postimg.cc/TY7kRHSD/Poster-Painting.webp",
    name: "POSTER PAINTING",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/156ni1_bVbYIrqVsqsHgvX9Hx44jdhiJVHh_y1alfjG8/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/11soLPsCLTTpbKDcWd9Y1Pr5R9Arx2NcSR6kK0wYF2Xo/edit"
  },
  {
    key: 9,
    url: "https://i.postimg.cc/dQWRdZBM/Treasure-Hunt.webp",
    name: "TREASURE HUNT",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/13qem_YPqdxiwRO8MvufGk_6LD00Dt5OYNZans0uyFTY/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/1XYF9wpFcRPI-LJ94tJM3rZN7AoNIcByrPRSDOokqeqI/edit"
  },
  {
    key: 10,
    url: "https://i.postimg.cc/fRdY62hZ/Paper-Presentation.webp",
    name: "PAPER PRESENTATION",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/1h6ebvxcx3rBvGhCjhi9JrCkBto5q1OLLtiTQE7UMYPo/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/1q8qCnqPu5VAq_1F9QpeJQBbq4CEl6HuQvZNpp1V4OpE/edit"
  },
  {
    key: 11,
    url: "https://i.postimg.cc/s2NQx5zK/Fun-With-Welding.webp",
    name: "FUN WITH WELDING",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/1jZtgFJ69xpd9fAumQFQ9llVHpo2tSEl1SArRisF_dxg/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/13X7L7YfbHRDgQR7A0ux2mUuiowEMKw1H49dAO_ZhdqQ/edit"
  },
  {
    key: 12,
    url: "https://i.postimg.cc/7hXKJBZj/Rangoli.webp",
    name: "RANGOLI",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/1Kpn655mx9GgR2CjsQ_OmKwJq_UW6NWkWeA0IpHj6LL8/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/1iXMWROytvk1MD7vlb534POMTuH_Pr7JE7MbLp6wXv8M/edit"
  },
  {
    key: 13,
    url: "https://i.postimg.cc/5tHDdM2y/Math-Olympiad.webp",
    name: "MATH OLYMPIAD",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/1A1U448LBcARexNBw_mG7Lc08-P5g_5iNJ-CPcF3vEMM/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/1dtaeohbBVYQMUNo29BnFOTJA4wpo8dZ04zHQeAt2emw/edit"
  },
  
  {
    key: 14,
    url: "https://i.postimg.cc/VkRMqv2y/Bridge-Design.webp",
    name: "BRIDGE DESIGN",
    venue: "gita garden",
    date: "01-02-24",
    desc: "Show your Codding skills",
    EventIncharge: "Xyz",
    EventCoordinators: ["ABC", "XYZ", "RST"],
    volunteers: ["Rohan", "Mohan", "Simran"],
    time: "12:15 pm",
    prize: "₹ 2000",
    sheets: "https://docs.google.com/spreadsheets/d/1navX5JYFsllV_Xd-g-p7tZUdWqpyGYa7W-gIvIrP-eE/edit?usp=sharing",
    form:"https://docs.google.com/forms/d/1t82DR4bvH3ebvktCrWWXNBBkOUHe8PfLnXUyJQC2XC0/edit"
  },
];

export default EventDetails;
